# Generated by Django 5.0.3 on 2024-05-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_email_alter_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(default='Not Set', max_length=128),
            preserve_default=False,
        ),
    ]
