# Generated by Django 5.0.3 on 2024-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='full_name',
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='Not Set', max_length=50),
            preserve_default=False,
        ),
    ]
